Increase column, show dash and use tooltip mobile
cowprotocol/explorer pull request #113
Opened 2022-06-08 02:20 UTC by henrypalacios

# Summary

Closes #109 

- [x] Expand the column to show the value in 1 line
- [x] Show 'dash' or so when there is no value in the column on mobile view
- [x] Display whole surplus amount on hover in a mobile view

# To Test

Open tx 0x2dB8323b3766b868AAF6a967E55eEb35C233DE9d

2022-06-08 08:54 UTC, elena-zh commented
Hi @henrypalacios , great changes!
I wonder if we could add a dash to the Surplus column when it is empty in a desktop version. 
WDYT?

Thanks!

2022-06-08 11:24 UTC, ramirotw approved these changes
nice!

2022-06-08 13:17 UTC, henrypalacios commented
Now that I see it again with the dash, it looks weird to me  :sweat_smile:

How do you think we can improve it @alongoni?

2022-06-08 23:10 UTC, alongoni requested changes

2022-06-08 23:10 UTC, alongoni commented on src/components/orders/OrderSurplusDisplay/index.tsx
> +      width: 3.4rem;
![image](https://user-images.githubusercontent.com/622217/172732370-dbb77ea9-c956-4f7d-9867-c1a513555ccb.png)
(see the Surplus amount at the right)
Maybe we need to set `width: 100%`; on mobile

2022-06-09 02:45 UTC, alongoni approved these changes
Looks great!!!

2022-06-09 07:59 UTC, elena-zh approved these changes
LGTM!

2022-06-14 12:34 UTC, merged