Fix order search in different networks
cowprotocol/explorer pull request #132
Opened 2022-06-21 21:55 UTC by ramirotw

# Summary

Closes #130

# To Test

1. Copy an orderID from Rinkeby
2. Switch to Gnosis chain
3. Navigate to the Home page
4. Search for the copied order

2022-06-22 13:24 UTC, matextrem requested changes

2022-06-22 13:24 UTC, matextrem commented on src/api/operator/operatorApi.ts
> +    order = await cowInstanceDev.cowApi.getOrder(orderId)
Could we move it to finally statement since we are using it both in try and catch ones.

2022-06-22 13:44 UTC, ramirotw commented
@elena-zh re-posting here your feedback from https://github.com/cowprotocol/explorer/issues/130#issuecomment-1162996669

> Hey @ramirotw , great changes!
However, I have noticed, that order TxHash does not appear when open a transaction for the 1st time using search in a different network. See the video: https://watch.screencastify.com/v/nuo4Q7xONKJ608sQ1UTj (the issue itself starts from 25s on the video)
Could you please take a look into this issue?

2022-06-22 14:15 UTC, elena-zh commented
seems that the fix was reverted
![image](https://user-images.githubusercontent.com/70885163/175051706-4e2fd460-cda1-40b5-b944-3b6df6f02d1e.png)

2022-06-22 15:11 UTC, matextrem approved these changes
LGTM 👍

2022-06-22 19:31 UTC, henrypalacios commented
It does not work for me!

When I search on GC the tx `0x5dd8cab9849abc9ff04230d3c7432fa9206fd5b47fd5cb704bc04775f4ec65a2b638eda8c10005cb456b1913ad60a8f3d6a927146144b0ea`  I got :point_down: 
![Selection_583](https://user-images.githubusercontent.com/4270166/175120766-2f410781-7878-48f1-9227-60eb0d12eba3.png)


It's a valid order on [mainnet](https://pr119--explorer.review.gnosisdev.com/orders/0x5dd8cab9849abc9ff04230d3c7432fa9206fd5b47fd5cb704bc04775f4ec65a2b638eda8c10005cb456b1913ad60a8f3d6a927146144b0ea)

2022-06-27 09:30 UTC, alfetopito approved these changes

2022-06-27 12:04 UTC, elena-zh requested changes
Hey @ramirotw , I can't load  a TX details page when I search for Rinkeby transaction in Ethereum. See the video: https://watch.screencastify.com/v/DRq2z7sKeGORMI8qYDeT

![cant load](https://user-images.githubusercontent.com/70885163/175936522-0347d79d-e281-4ec6-995d-32ffc61a3560.jpg)

Refreshing the page helps, though.

Could you please take a look at it? 

Here were my steps: 
1. Open user details in Rinkeby
2. Copy an order ID from the list
3. Open Home page in Ethereum
4. Search for a copied order ID

2022-06-27 19:33 UTC, ramirotw commented
> Hey @ramirotw , I can't load a TX details page when I search for Rinkeby transaction in Ethereum. See the video: https://watch.screencastify.com/v/DRq2z7sKeGORMI8qYDeT

This was caused by the hook that fetches the tokens. The tokens fetch was triggered while still on the mainnet and set a loading flag to true, but when on rinkeby it didn't re-run, so it stayed on loading indefinitely.

2022-06-28 08:37 UTC, elena-zh commented
Hey @ramirotw !
The issue is partially fixed, as search for: 
 - Rinkeby transaction in GC- works fine
 - Mainnet transaction in GC 0 works fine
 - GC transaction in Rinkeby - works fine.
BUT search for
 - GC transaction in Mainnet - not working
 - Rinkeby transaction  in Mainnet- not working
 - Mainnet transaction in Rinkeby - not working

Besides, I have found a strange issue with orders list pagination in this Pr: https://watch.screencastify.com/v/YSoUCU7TRfQcyJ0yElph

Thanks!

2022-06-28 12:40 UTC, elena-zh commented
@ramirotw , search for orders IDs look good to me now!

However, amounts for TX details are not loaded in this PR when search for transactions from different networks. Could you please take a look at it, as the issue is not reproducible in #137

2022-06-28 14:59 UTC, elena-zh commented
> @ramirotw , search for orders IDs look good to me now!
> 
> However, amounts for TX details are not loaded in this PR when search for transactions from different networks. Could you please take a look at it, as the issue is not reproducible in #137 ![image](https://user-images.githubusercontent.com/70885163/176190245-c5ab6ecc-7612-4ba2-91ae-56f06674ed71.png)

Steps to reproduce it: 
1. Copy a Tx hash of a filled order in Gnosis chain
2. Open Home page in Ethereum
3. Paste the copied TxHash from GC into the search field and search for it. 

**AR**: Tx details page is opened, but amounts are not loaded

2022-06-28 22:17 UTC, ramirotw commented
@elena-zh please re-test

2022-06-29 09:45 UTC, ramirotw commented
> @ramirotw , order search does not work at all (order from a different network)

A commit didn't apply while rebasing 🤦‍♂️, my bad sorry

2022-06-29 10:04 UTC, elena-zh approved these changes

2022-06-29 10:13 UTC, merged