[Top Tokens Table] Rename some columns
cowprotocol/explorer pull request #197
Opened 2022-08-22 17:17 UTC by matextrem

# Summary

Closes #152 

Rename some columns in Top Tokens table

<img width="1170" alt="Screen Shot 2022-08-22 at 14 17 22" src="https://user-images.githubusercontent.com/11525018/185980805-0980e2a6-9601-4886-b4b6-50a09e117b7e.png">

# To Test

1. Open the `home` page.
* You'll notice some columns have been renamed in Top tokens table: 
     - 24h -> Price (24h)
     - 7d -> Price (7d)
     - 24h Volume -> Volume (24h)
     - Last 7 days -> Price (last 7 days)

2022-08-22 17:34 UTC, ramirotw requested changes
mobile view still has old headers

2022-08-23 10:56 UTC, elena-zh approved these changes

2022-08-23 13:07 UTC, ramirotw approved these changes

2022-08-23 13:08 UTC, ramirotw commented
LGTM, @matextrem remember to Squash commits

2022-08-23 14:29 UTC, alfetopito approved these changes

2022-08-23 16:58 UTC, merged