[App Data] Add more context
cowprotocol/explorer pull request #204
Opened 2022-08-30 12:50 UTC by matextrem

# Summary

This PR add more context to the AppData page for the Encode and Decode tabs.

<img width="1193" alt="Screen Shot 2022-08-30 at 09 49 02" src="https://user-images.githubusercontent.com/11525018/187440887-a9b015d3-ff4e-43c1-b307-d3a6f5f48848.png">
<img width="1175" alt="Screen Shot 2022-08-30 at 09 49 22" src="https://user-images.githubusercontent.com/11525018/187440906-b3539b98-a60f-4bca-a4b5-96686b18aaad.png">
<img width="1204" alt="Screen Shot 2022-08-30 at 09 49 34" src="https://user-images.githubusercontent.com/11525018/187440921-33aa9018-a9db-469b-89e1-e5cbdf3da8dd.png">

# To Test

1.  Open the page `appdata`
     * You'll notice a message on the top of the `appdata` form.
2.  Generate an appdata document.
     * You'll notice a message on the top of the `IPFS` form.
3. Go to Decode tab
     * You'll notice a message on the top of the `appdata hash` form.

2022-08-31 10:34 UTC, alfetopito reviewed
Thanks Mati!

I've created a doc to track the suggestions and also shared with the broader team https://docs.google.com/document/d/1yeHOtzCU2dPugGA0yXDao3OLnhyOUgFqWQJ97sZDz-8/edit#heading=h.rwdqhsd04zq0

Let's give them a day to give us some feedback

2022-08-31 10:55 UTC, elena-zh commented
Hey @matextrem , while the doc with texts is under discussion, here are some my UI issues: 
1. It would be great to open an external link in a new tab (as we do everywhere in the app)
![another tab](https://user-images.githubusercontent.com/70885163/187661566-ae490478-6c6e-4d5e-bc68-8a43ce708bcd.jpg)
2. The text seems like clued to the top boarder in a tablet/mobile views
![tablet - clued](https://user-images.githubusercontent.com/70885163/187661636-55e2ac42-641a-4492-9bba-5cb0cc764d07.jpg)

And now I feel that the form is overloaded with texts. Maybe we should put explanations into some kind of special containers to separate what is a section description/context data, Or change a description text color, WDYT?

Thanks!

2022-09-01 11:17 UTC, alongoni commented
> @elena-zh Regarding the third comment, I do think the same but IDK what is the best way to improve it. @alongoni any suggestions?
Maybe something like this could work?
![Screenshot from 2022-08-31 14-39-30](https://user-images.githubusercontent.com/622217/187901455-d69a9174-1a7c-4234-84f3-08be236fc356.png)
cc @elena-zh @matextrem

2022-09-05 11:30 UTC, elena-zh commented
Hey @matextrem , some more new issues :)
1. When I press to Decode button, the app is reloaded and is back to the Home page
![decode](https://user-images.githubusercontent.com/70885163/188438513-396c8725-8019-44e6-824e-b985a69ce8d8.jpg)
2. Decode section does not look good now when I press on the Decode button
![decode data](https://user-images.githubusercontent.com/70885163/188438599-679a3794-1b80-4f69-a701-8cc845a368b8.jpg)
3. Maybe we should use the same font options for these texts? To clarify: I'm in favor of the text option at the bottom of the section.  WDYT?
![the same text options](https://user-images.githubusercontent.com/70885163/188438883-1cfb6087-d75d-4b54-bf54-48ae841deece.jpg)

Thanks!

2022-09-05 19:50 UTC, ramirotw requested changes
1. The Decode tab header seems to be broken once the hash is decoded

<img width="887" alt="image" src="https://user-images.githubusercontent.com/3328006/188506709-b6b3f2df-e05b-4d8d-af76-204c0d2341c8.png">

2. What is the point of the `AppData*` form header? For me that form is too verbose
<img width="308" alt="image" src="https://user-images.githubusercontent.com/3328006/188506874-8efe02e8-a8ee-49d5-b8f4-dd996668017b.png">

2022-09-06 11:00 UTC, elena-zh commented
Hey @matextrem , 
agree with @ramirotw : it would be great to move json section to the bottom and do not show it near the page description. 
Also, my nitpick is to reduce the distance between lines in this description
![line height](https://user-images.githubusercontent.com/70885163/188615920-ee5e5b59-0615-4279-8837-760c391f27fb.jpg)

2022-09-07 03:35 UTC, matextrem commented
> 1. The Decode tab header seems to be broken once the hash is decoded
> 
> <img alt="image" width="887" src="https://user-images.githubusercontent.com/3328006/188506709-b6b3f2df-e05b-4d8d-af76-204c0d2341c8.png">
> 
> 2. What is the point of the `AppData*` form header? For me that form is too verbose
> 
> <img alt="image" width="308" src="https://user-images.githubusercontent.com/3328006/188506874-8efe02e8-a8ee-49d5-b8f4-dd996668017b.png">

@ramirotw That's the name of the field. Should I remove it ?

2022-09-07 10:52 UTC, elena-zh approved these changes
Hey @matextrem , changes LGTM!
Btw, while testing I have found a regression issue #208 , so it would be great to address it a bit later. 

Thanks!

2022-09-07 13:07 UTC, matextrem commented
> > @ramirotw That's the name of the field. Should I remove it ?
> 
> 
> 
> I feel there's too much text for just one field, now that we have the description on top of the page maybe 4 rows is a lot.
> 
> 
> 
> <img width="276" alt="image" src="https://user-images.githubusercontent.com/3328006/188865420-260cd044-0413-4832-9f27-36dcb4b6911b.png">
> 
> 
> 
> Btw, why aren't we using 100% of the width?
> 
> 
> 
> <img width="890" alt="image" src="https://user-images.githubusercontent.com/3328006/188865276-b6896706-966b-4838-a7d1-cc26b0e3c8fb.png">
> 
> 

@ramirotw maybe we could remove one of the description instead. 

Regarding de second point, I didn't change it from how it was before. I can change it to be 100% of the width though.

2022-09-09 11:44 UTC, ramirotw requested changes
Almost there, the elements should be left aligned so we are consistent with the Order Details page. Also the JSON container should have the same width as the hash.
<img width="908" alt="image" src="https://user-images.githubusercontent.com/3328006/189342508-35cd4190-6d9c-45a3-85a1-3d5d1e665344.png">

<img width="768" alt="image" src="https://user-images.githubusercontent.com/3328006/189342640-4de371be-3228-46b8-b10d-55447d522bdd.png">

2022-09-12 09:47 UTC, elena-zh commented
Changes LGTM!

2022-09-12 13:20 UTC, ramirotw approved these changes
👍

2022-09-12 15:57 UTC, alongoni approved these changes
Great work! 

Just a small detail:
![image](https://user-images.githubusercontent.com/622217/189700407-bf4597e3-8f2e-4db5-a56d-beac39166a09.png)

The json section notes should have the same font-size than the form.

2022-09-12 17:36 UTC, merged