[Tokens Table] Change query to use tokenHourlyTotals for tokens table
cowprotocol/explorer pull request #211
Opened 2022-09-08 15:08 UTC by matextrem

# Summary

Closes #148 

Changed the `tokenDailyTotals` query by `tokenHourlyTotals` to increase data points in the chart.

<img width="1218" alt="Screen Shot 2022-09-08 at 12 00 15" src="https://user-images.githubusercontent.com/11525018/189157890-1566fa4d-d137-487d-b59b-0095e74650bd.png">

# To Test

1. Open the `home` page
    * Look at `Price (Last 7 days)` column. Data points in the chart have been increased to improve precision.

2022-09-08 16:34 UTC, ramirotw requested changes
There a few things left:

1. The query should be updated. The `tokenDailyTotals` doesn't make any sense. Also the `tokenHourlyTotals` is capped to the last 25 records, we should probably remove that.
```graphql
query GetHistoricalData($address: ID!, $lastDayTimestamp: Int!, $lastWeekTimestamp: Int!) {
    tokenHourlyTotals(
      first: 25
      orderBy: timestamp
      orderDirection: desc
      where: { token: $address, timestamp_gt: $lastDayTimestamp }
    ) {
      token {
        address
      }
      timestamp
      totalVolumeUsd
      averagePrice
    }

    tokenDailyTotals(
      first: 8
      orderBy: timestamp
      orderDirection: desc
      where: { token: $address, timestamp_gt: $lastWeekTimestamp }
    ) {
      token {
        address
      }
      timestamp
      averagePrice
    }
  }
```
2. The types should also be updated:
```typescript
export type TokenDailyTotals = {
  token: { address: string }
  timestamp: number
  totalVolumeUsd: string
  averagePrice: string
}

export type TokenWeeklyTotals = {
  token: { address: string }
  timestamp: number
  averagePrice: string
}

export type SubgraphHistoricalDataResponse = {
  tokenHourlyTotals: Array<TokenDailyTotals>
  tokenDailyTotals: Array<TokenWeeklyTotals>
}
```
3. Remove the console.log in https://github.com/cowprotocol/explorer/blob/d99c4d43bb7e160abdd9ac59bd4c1badf814b79e/src/hooks/useGetTokens.ts#L283

2022-09-09 10:14 UTC, ramirotw commented on src/hooks/useGetTokens.ts
>    tokenHourlyTotals: Array<TokenDailyTotals>
lets rename `TokenDailyTotals` to `TokenHourlyTotals`

2022-09-09 10:55 UTC, elena-zh reviewed
LGTM!

2022-09-09 10:55 UTC, elena-zh approved these changes

2022-09-09 19:46 UTC, ramirotw approved these changes
Awesome! Remember to squash!

2022-09-09 20:07 UTC, merged