[Tokens Table] Sort by 24h volume
cowprotocol/explorer pull request #213
Opened 2022-09-14 03:44 UTC by matextrem

# Summary

Closes #210 

- Refactor code to get tokens table info in just one query to the subgraph.
- Sort the tokens table by 24h Volume instead of Total Volume.

<img width="1251" alt="Screen Shot 2022-09-14 at 00 38 18" src="https://user-images.githubusercontent.com/11525018/190054577-4d8917c6-5c7c-4a07-bcee-562adf627cfb.png">

# To Test

1.  Open the `home` page and wait for the tokens table to load.
*  You'll see the tokens table is now sorted by 24h volume.

2022-09-14 11:45 UTC, elena-zh commented
Hey @matextrem , cool changes!
Happy to see the arrow that currently shows a default sorting on the table!

However, the arrow is shifted to the 2ns line when the table is displayed on a reduced screen. Can we fix it somehow?
![another line](https://user-images.githubusercontent.com/70885163/190144616-615af014-ca37-44ee-8a55-3c802b226398.jpg)

Also, the arrow looks weird (from my perspective) in a mobile view. It is displayed on each card, and it is not clear that it shows a default sorting
![do not show on mobile](https://user-images.githubusercontent.com/70885163/190144802-fd6ab5e2-8478-444f-9165-54615c9b8a60.jpg)
Maybe we should remove it from the mobile view and just type something like "Sorted by Volume (24h)' under the search field?
![image](https://user-images.githubusercontent.com/70885163/190145141-82a9ca86-0387-46fa-bce8-c17ca47d93fb.png)

@alongoni , @matextrem , WDYT?

Thanks!

2022-09-14 12:28 UTC, ramirotw requested changes
Looking good!

A few notes:

1. Check how the `Price (24h)` and `Price (7d)` values are calculated, we have that data through the hourlyTotals field so it shouldn't be empty
<img width="889" alt="image" src="https://user-images.githubusercontent.com/3328006/190146833-a1cbf405-fd07-4ec0-b405-ee9d54122e65.png">

2. The last updated timestamp isn't too clear. Could you move the timestamp to the next line and add also minute precision: `Last Updated: 2022-09-13 21:30h`
<img width="884" alt="image" src="https://user-images.githubusercontent.com/3328006/190147382-033296af-55ea-4039-b702-f3bf64dec48c.png">

3. The averagePrice that is picked in:

```js
    const priceUsd = data.tokenHourlyTotals[0]?.averagePrice
```

is now wrong as the `tokenHourlyTotals` array is sorted in ascending order and you are now picking the last week price and not the current one.

4. is the `addHistoricalData` function still needed? I added that because we were using 2 different queries to build the table, but now we can do just 1 query for everything, couldn't we just use the `processTokenData` or similar?

2022-09-14 12:28 UTC, ramirotw commented on src/hooks/useGetTokens.ts
> +      lastDayUsdTimestamp: lastDayTimestampFrom,
what's this `lastDayUsdTimestamp` value? is that the Last Updated timestamp value? If so, shouldn't this be picked from the `timestamp` value response?

2022-09-15 04:53 UTC, matextrem commented
@elena-zh regarding the first comment, I cannot find a solution for this. Maybe @alongoni can come out with an idea. 
@ramirotw I checked the way the values are calculated and it seems to be fine (I checked it in https://explorer.cow.fi/ and some values are undefined as well). IDK if we are doing something wrong with the query though.

2022-09-15 08:51 UTC, alfetopito commented
Did not check the code yet, but one thing that confuses me:
<img width="1174" alt="Screen Shot 2022-09-15 at 10 49 16" src="https://user-images.githubusercontent.com/43217/190359644-c3fc568a-ec2e-4ab9-881c-c71836522fcf.png">

We are on the 15th, but the top token was last updated on the 11th?
Maybe this is more of a Graph question, but the data does not look accurate

2022-09-15 09:12 UTC, alfetopito reviewed
Just a small nitpick

2022-09-15 09:12 UTC, alfetopito commented on src/hooks/useGetTokens.ts
> +          const tokensData = {} as { [tokenId: string]: TokenData }
What about:

```suggestion
          const tokensData: { [tokenId: string]: TokenData } = {}
```

2022-09-15 10:50 UTC, elena-zh commented
Hey @matextrem , I think that the easiest way to fix the issue with the arrow is to remove a space between the label and the arrow
![image](https://user-images.githubusercontent.com/70885163/190383408-3e238c41-34ea-4828-86b4-e797005f62b5.png)

My bad, I did not mentioned it in the previous comment, but it would be great to add a way of sorting to the mobile view: Sorted by Volume(24h): from highest to lowest (or so). WDYT?

As for values that are displayed in Tokens tables in Dev and in the current PR, they appear to be different. I suppose that they should be the same
![image](https://user-images.githubusercontent.com/70885163/190385393-b140b1e0-b3e5-487c-88f5-e6cd8038e5b1.png)

2022-09-16 11:36 UTC, elena-zh commented
Hey @matextrem , 
The arrow LGTM. 
Tokens last updated date looks great, however, I'd not start 'Updated' with the capital letter. 
![image](https://user-images.githubusercontent.com/70885163/190629693-8ed77dbb-fc67-4e76-ad59-b485d3586b6f.png)

The same is for 'From highest to lowest": it would be great not to start From with the capital letter. 

As for amounts and numbers in the table. they still look different in comparison with the Dev app version. 
![ыешдд ыуу вуааукутсув](https://user-images.githubusercontent.com/70885163/190630012-945e400f-8822-4ee7-afe2-7420b7ab6f81.jpg)
And now there is a difference in 24h volumes. Frankly, I can't find how to check the daily token volume in the graph,       maybe you could help me with a request to check what number is a correct one. 
Anyways, I think that numbers should match...

Thanks

2022-09-19 11:06 UTC, elena-zh commented
Hey @matextrem , changes look better! 
I can see matching amounts in Price(24h) column now. 
But still  see that amounts are differ for Price (7d) and Volume (24h) columns ![image](https://user-images.githubusercontent.com/70885163/191003970-1559dd51-130e-4f73-a014-4697ec5b8c75.png)

Could you please take a look at it? 

Thanks

2022-09-19 20:30 UTC, ramirotw commented
> And now there is a difference in 24h volumes. Frankly, I can't find how to check the daily token volume in the graph, maybe you could help me with a request to check what number is a correct one.
> Anyways, I think that numbers should match...

@elena-zh To test the values you can run [this](https://api.thegraph.com/subgraphs/name/cowprotocol/cow/graphql?query=query+%28%24address%3A+String%2C+%24from%3A+Int%2C+%24to%3A+Int%29+%7B%0A%09tokenHourlyTotals%28%0A%09%09orderBy%3A+timestamp%0A%09%09orderDirection%3A+desc%0A%09%09where%3A+%7B+token%3A+%24address%2C+timestamp_gte%3A+%24from%2C+timestamp_lt%3A+%24to+%7D%0A%09%29+%7B%0A%09%09timestamp%0A%09%09totalVolumeUsd%0A%09%7D%0A%0A%09tokenDailyTotals%28%0A%09%09where%3A+%7B+token%3A+%24address%2C+timestamp_gte%3A+%24from%2C+timestamp_lt%3A+%24to+%7D%0A%09%29+%7B%0A%09%09timestamp%0A%09%09totalVolumeUsd%0A%09%7D%0A%7D%0A) query. You'd need to pass 3 variables:

```json
{
  "address": "0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48",
  "from": 1663459200, // yesterday
  "to": 1663545600 // today
}
```

Where address is the token address you want to check and from and to are Unix timestamps. For the Unix timestamps you can use https://www.epochconverter.com, keep in mind that to mimic how the app is getting the data you need to set 00:00hs UTC of today vs yesterday.

Regarding what we have now in prod vs what this PR changes, the values are going to be different as to implement the sorting by 24hs volume and the way the subgraph works, the data is aggregated daily, so now we are showing the volume from yesterday (before the volume was dynamic based on the moment the user entered the Explorer, so values could change if the user visited the app during the morning vs the afternoon)

2022-09-20 10:06 UTC, elena-zh commented
Hey @ramirotw , @matextrem , thanks for fixes and explanation. 
Now I see that numbers are not so differ as on the screenshots I attached above, and look more or less aligned given the fact that they will be different on Prod and in the pr. 

Just a tiny issue I'd like to report is that it would be great to make the date format look nicer 
![readable format](https://user-images.githubusercontent.com/70885163/191230186-3181c100-a090-403a-9d03-95e016a58261.jpg)
As an example, make it the same as we use on tooltips for other dates on Explorer
![fromat](https://user-images.githubusercontent.com/70885163/191230327-4946bf36-70c0-4ed0-a9f9-318cc0404f47.jpg)

Thanks

2022-09-20 12:40 UTC, elena-zh approved these changes
Approved now!

2022-09-20 12:59 UTC, ramirotw approved these changes

2022-09-21 01:43 UTC, merged

2022-09-26 10:52 UTC, alfetopito reviewed
Looking great now