236/solvers details
cowprotocol/explorer pull request #241
Opened 2022-10-21 04:25 UTC by matextrem

# Summary

Closes #236 

Added Solver details page.

<img width="1112" alt="Screen Shot 2022-10-21 at 01 20 55" src="https://user-images.githubusercontent.com/11525018/197111646-9044779e-0bd7-480d-93f2-694870478ff1.png">

# To Test

1.  Open the page `solvers`
2. Click on any solver name either in Active solvers or Settlements table
   * You'll be redirected to the solver details page.

*Disclaimer: There are some info left we have to update such as ETH cost and Active since box (it is harcoded right now)*

2022-10-21 10:38 UTC, elena-zh commented
Hey @matextrem , nice changes!
List of issues from my side: 
1. Full date on the Active since card does not match the format we use for full dates across the app
![вфеу ащкьфе](https://user-images.githubusercontent.com/70885163/197174365-7aeb5757-a53e-47b8-9030-1e253a4bee61.jpg)
2. There is no Solver name when open the page from Settlements tab
![name](https://user-images.githubusercontent.com/70885163/197175759-3ce1ea36-38c4-44ea-a256-4b1160f54b9a.jpg)
3. Frankly, it is not clear to me why we show full amounts on cards when press on Tooltips icons.
![image](https://user-images.githubusercontent.com/70885163/197175033-cd0dd795-ab62-4ca6-bb27-a4dac14b742b.png)
 We show amounts on hover, and tooltips icons should open explanation modals for this or that field 
![image](https://user-images.githubusercontent.com/70885163/197174936-88e27886-23f0-489f-8ad7-cf506c385712.png)

4. I think, it would be great to show a better message when a request to load the page data fails (error loading data, please try again?)
![failed - error](https://user-images.githubusercontent.com/70885163/197175205-a45b8044-8bac-4490-beba-0fad39a06706.jpg)
5. When Trades amount is not loaded, it shows NaN instead of 0
![nan when no data](https://user-images.githubusercontent.com/70885163/197175351-38da4316-c99f-4887-adfd-2678b789a3fc.jpg)
6. When open Solver details page from Active solvers tab in Ethereum, all dates are in June 
![june](https://user-images.githubusercontent.com/70885163/197175540-354ae116-a1be-4d8d-be49-e188e55a31d8.jpg)
7. Ethereum + Active solvers tab: the last solver in the list does not have a name, so the name is not clickable
![no name - address](https://user-images.githubusercontent.com/70885163/197174470-ceaf6df6-ad7d-49fa-b8d4-36dfb6aa6854.jpg)

9. There are no names for solvers in Gorli
![gorli no names](https://user-images.githubusercontent.com/70885163/197175804-65ef4580-154b-4c84-8295-047ffcf1e006.jpg)
10. It is impossible to load data for single solvers page from Active Solvers tab in Gnosis chain
![image](https://user-images.githubusercontent.com/70885163/197176032-9854da3d-00ba-4ee6-963f-2a7301a4c070.png)
11. Some token icons (like GNO) are dark
![dark tokens](https://user-images.githubusercontent.com/70885163/197176139-a1eeb66f-ffcf-48bc-8ed4-717114c3c2e4.jpg)
12. Text on cards should be better aligned in a tablet/mobile view
![cards better align](https://user-images.githubusercontent.com/70885163/197176372-70e74112-f0c4-45f2-ac80-5af238cf4dad.jpg)
13. Name and a solver address are not aligned in a real iOS device
![mobile](https://user-images.githubusercontent.com/70885163/197176552-66580d31-f29e-4549-b1cf-abfdffb522ca.jpg)

2022-10-21 13:04 UTC, elena-zh requested changes
See the notes above

2022-10-21 18:59 UTC, matextrem commented
hey @elena-zh  I addressed some of the bugs you shared.

Regarding 1 & 3 it needs to be changed. I left it is since we need to discuss what to put in there. maybe @alongoni could help us in it.

4. We have a notification in place when there is an error. Those errors you are seeing are related to the icons not able to being loaded but it is not related to the solver details info itself.

6. Is that wrong? I opened up another solver and it showed me dates in May. cc: @ramirotw 

7. There is no name for that solver. Now, we are showing the address instead.

8. I didn't find the SQL query to fetch solvers name for Gorli. I tried to use the same we are using for Ethereum but the addresses don't match. cc: @alfetopito 

9. Yes, we are not getting any info related settlements for Gnosis chain (Subgraph is only returning the ids). cc @ramirotw 

10. It was fixed in this [PR](https://github.com/cowprotocol/explorer/pull/235). When merged, it will be reflected in this PR as well.

2022-10-21 20:36 UTC, ramirotw commented on src/hooks/useGetSettlements.ts
> +          solverAddress ? { solver: solverAddress } : undefined,
`solverAddress` should be lowercased, the subgraph doesn't work with checksummed addresses 

<img width="404" alt="image" src="https://user-images.githubusercontent.com/3328006/197284174-90704a9c-3e60-4742-893a-9fbe2f17d54b.png">

2022-10-21 20:49 UTC, ramirotw commented
> When open Solver details page from Active solvers tab in Ethereum, all dates are in June

@matextrem @elena-zh This is because that solver was deactivated but the subgraph currently is not handling the toggle of the isSolver flag to false. There's a pending PR in https://github.com/cowprotocol/subgraph/pull/65 to fix that. 

To validate whether a mainnet solver is active or not using onchain data:

1. Go to https://etherscan.io/address/0x2c4c28ddbdac9c5e7055b4c863b72ea0149d8afe#readProxyContract
2. In the `isSolver` section, paste the solver address
3. If the `bool` response is `true` then it's active, if empty it's not

2022-10-21 20:54 UTC, ramirotw commented
> It is impossible to load data for single solvers page from Active Solvers tab in Gnosis chain

@matextrem this issue is related to https://github.com/cowprotocol/explorer/pull/241#discussion_r1002167320

2022-10-24 10:36 UTC, elena-zh commented
> > When open Solver details page from Active solvers tab in Ethereum, all dates are in June
> 
> @matextrem @elena-zh This is because that solver was deactivated but the subgraph currently is not handling the toggle of the isSolver flag to false. There's a pending PR in [cowprotocol/subgraph#65](https://github.com/cowprotocol/subgraph/pull/65) to fix that.
> 
> To validate whether a mainnet solver is active or not using onchain data:
> 
> 1. Go to https://etherscan.io/address/0x2c4c28ddbdac9c5e7055b4c863b72ea0149d8afe#readProxyContract
> 2. In the `isSolver` section, paste the solver address
> 3. If the `bool` response is `true` then it's active, if empty it's not

That is ridiculous :)
The tab name is 'Active solvers'. but we show deactivated solvers at the top of the table.

2022-10-24 10:49 UTC, elena-zh commented
Hey @matextrem , thanks for the explanation. 
Here are my notes: 
1. For the cases 1, 3, agree, let waif for @alongoni input here
2. 8 case `There are no names for solvers in Gorli`: why can't we show solvers addresses instead? 
3. 9 case: `'It is impossible to load data for single solvers page from Active Solvers tab in Gnosis chain'`: I believe, it is going to be fixed
4. 11 case `Text on cards should be better aligned in a tablet/mobile view`: still relevant
![mobile cards](https://user-images.githubusercontent.com/70885163/197509367-48e8464e-4a64-4a50-8440-765171fb070e.jpg)
5. 12 case: looks much better, but still the address is not placed in 1 line with a solver name
![not in 1 line](https://user-images.githubusercontent.com/70885163/197509504-9e816ef7-a5ed-46db-8066-b2a11613293d.jpg)

Thank you!

2022-10-24 13:08 UTC, ramirotw commented
> That is ridiculous :)
> The tab name is 'Active solvers'. but we show deactivated solvers at the top of the table.

Indeed it's ridiculous, but this is for internal testing before @GabrielCamba deploys the changes to fix it.

2022-10-25 15:53 UTC, alfetopito commented
Looking good so far.

Comments about current progress:

1. Invert the position of `timestamp` and `tx hash` columns
![Screen Shot 2022-10-25 at 16 45 12](https://user-images.githubusercontent.com/43217/197820487-585fc24f-2da9-493a-8c18-b3b5ae2e5ece.png)
2. For the tooltips in the solvers detail page, I'm inclined to either: Not show the tool tip OR put a brief and somewhat redundant explanation like
 - Trades: Total trades settled by this solver
 - Total volume: Total volume settled by this solver
 - Total settlements: Total settlements by this solver
 - Active since: When the solver became active as was able to submit solutions

3. For the `Trades` card, add `Total` => `Total trades`


And I have a question: are we also limiting the # of settlements we load per individual solver to 1000 like it's done in the general settlements page?

2022-10-25 15:57 UTC, alfetopito commented
Request for a follow up PR:

Update the overall search so when a solver address is searched it leads to the solver details page.

For example. Searching on https://pr241--explorer.review.gnosisdev.com/gc for `0x7942a2b3540d1eC40B2740896f87aEcB2a588731` (Quasimodo's address) should lead you to https://pr241--explorer.review.gnosisdev.com/gc/solvers/0x7942a2b3540d1eC40B2740896f87aEcB2a588731 rather than https://pr241--explorer.review.gnosisdev.com/gc/address/0x7942a2b3540d1eC40B2740896f87aEcB2a588731

2022-10-25 16:02 UTC, alfetopito commented on src/apps/explorer/components/SettlementsTableWidget/index.tsx
> +  const filteredSettlements = useFlexSearch(query, settlements, ['name', 'txHash'])
Can the search have some debounce?

2022-10-26 09:58 UTC, elena-zh commented
> Update the overall search so when a solver address is searched it leads to the solver details page.
> 
> For example. Searching on https://pr241--explorer.review.gnosisdev.com/gc for `0x7942a2b3540d1eC40B2740896f87aEcB2a588731` (Quasimodo's address) should lead you to https://pr241--explorer.review.gnosisdev.com/gc/solvers/0x7942a2b3540d1eC40B2740896f87aEcB2a588731 rather than https://pr241--explorer.review.gnosisdev.com/gc/address/0x7942a2b3540d1eC40B2740896f87aEcB2a588731

Hey @alfetopito , I have created #244 task for this

2022-10-26 10:11 UTC, elena-zh commented
Hey @matextrem , cases 1, 2, 4, 5 from this [comment ](https://github.com/cowprotocol/explorer/pull/241#issuecomment-1288846978)are still not fixed.

Besides, I have another question: since the number of trades is limited with 1000 now, should we show this card on the UI? In most of cases it will always show 1K until we implement a solution how to show more data
![will be always 1k](https://user-images.githubusercontent.com/70885163/198000022-3efdbb91-3155-491f-8230-14a4f0723b9d.jpg)

2022-10-26 12:20 UTC, ramirotw commented
> Hey @matextrem , cases 1, 2, 4, 5 from this [comment ](https://github.com/cowprotocol/explorer/pull/241#issuecomment-1288846978)are still not fixed.
> 
> Besides, I have another question: since the number of trades is limited with 1000 now, should we show this card on the UI? In most of cases it will always show 1K until we implement a solution how to show more data
> ![will be always 1k](https://user-images.githubusercontent.com/70885163/198000022-3efdbb91-3155-491f-8230-14a4f0723b9d.jpg)
> 
> 

FYI the Total Settlements number will be updated once the subgraph update is deployed, hopefully by the EOW.

2022-10-26 17:54 UTC, matextrem commented
> Looking good so far.
> 
> Comments about current progress:
> 
> 1. Invert the position of `timestamp` and `tx hash` columns
>    ![Screen Shot 2022-10-25 at 16 45 12](https://user-images.githubusercontent.com/43217/197820487-585fc24f-2da9-493a-8c18-b3b5ae2e5ece.png)
> 2. For the tooltips in the solvers detail page, I'm inclined to either: Not show the tool tip OR put a brief and somewhat redundant explanation like
> 
> * Trades: Total trades settled by this solver
> * Total volume: Total volume settled by this solver
> * Total settlements: Total settlements by this solver
> * Active since: When the solver became active as was able to submit solutions
> 
> 3. For the `Trades` card, add `Total` => `Total trades`
> 
> And I have a question: are we also limiting the # of settlements we load per individual solver to 1000 like it's done in the general settlements page?

Yes, we are limiting the amount of settlements to 1000 as well.

2022-10-26 17:58 UTC, matextrem commented
> Hey @matextrem , cases 1, 2, 4, 5 from this [comment ](https://github.com/cowprotocol/explorer/pull/241#issuecomment-1288846978)are still not fixed.
> 
> Besides, I have another question: since the number of trades is limited with 1000 now, should we show this card on the UI? In most of cases it will always show 1K until we implement a solution how to show more data ![will be always 1k](https://user-images.githubusercontent.com/70885163/198000022-3efdbb91-3155-491f-8230-14a4f0723b9d.jpg)

Hey @elena-zh!  I updated the branch with the feedback.

Regarding point 2, It's working for me. 

Regarding 5, I don't fully understand what's the behavior you want here. They are vertically centered on Tablet/Mobile view : 

<img width="843" alt="Screen Shot 2022-10-26 at 14 56 58" src="https://user-images.githubusercontent.com/11525018/198101134-bfb1f0c2-8a6f-4f89-8a36-a2590b9f98c8.png">

Maybe @alongoni could give feedback on this as well.

2022-10-27 10:02 UTC, elena-zh commented
Hey @matextrem , overall, changes look good to me. But: 

> Regarding point 2, It's working for me.

Please, take a look at the Settlements tab. Active solvers tab looks good. 
![image](https://user-images.githubusercontent.com/70885163/198251974-75b393b4-42af-4a6d-9d5c-db24dd0cec1e.png)

Thanks!

2022-10-27 18:08 UTC, matextrem commented
@elena-zh updated!

2022-10-28 10:13 UTC, elena-zh approved these changes
Hey @matextrem , changes LGTM now. 
We still have issues related to the Supgraph: 
 - Total settlements are 1000 for a single solver, and on Settlements table
 - No ETH cost
 - Do 'Active since'

Also, I have created a separate task to adjust pagination displaying on tables across the whole app #246. 

Thanks

2022-10-30 20:23 UTC, merged