Ipfs gateway
cowprotocol/explorer pull request #475
Opened 2023-05-03 18:37 UTC by anxolin

# Summary

Modifies the gateway so we don't depend on Gnosis one any more. 

We default to cloudflare, however, this will be modified by ENV so we use https://ipfs.cow.fi/ipfs

This PR adds the required ENV variable

## Related PR
Related to this PR, i had to do this PR to allow me to modify the IPFS gateway

https://github.com/cowprotocol/app-data/pull/24

##  Technical note
Fixed Elena's reported problem, apparently, it was a non-configurable property, and we were trying to delete it.

If you are curious, I'm using this to check if it can be deleted before doing so
https://github.com/cowprotocol/explorer/pull/475

# To Test
1. Make sure the app-data in the orders is loaded ~using https://ipfs.cow.fi/ipfs~ using Cloudflare (since our gateway has some permission issues

https://explorer-dev-git-ipfs-gateway-cowswap.vercel.app/orders/0x31dda03282cbf2010826c0bd95bc6fcb050969142b6fb8d4f870b6c32a0bf211fbe87d602f7d7dd511349be4acf58842392124a06452a858?tab=overview

![image](https://user-images.githubusercontent.com/2352112/236185467-acd2d44a-dfe1-4f3e-b05a-d3b2e1d3eaf4.png)

2023-05-04 08:50 UTC, alfetopito reviewed
Can we make a regular release instead?
There are minimal changes of low impact pending to be released

2023-05-04 13:47 UTC, elena-zh requested changes
Appdata page is not working in the PR https://explorer-dev-git-ipfs-gateway-cowswap.vercel.app/appdata?tab=encode
![image](https://user-images.githubusercontent.com/70885163/236226805-7dc2f6c7-42f5-4ab4-849d-5e9de5ca18c6.png)

2023-05-05 09:37 UTC, anxolin commented
Thanks @elena-zh ! this error was un-expected, since I'm only changing the URL. I did a small change to make it more resilient. 

I tested to update a document to IPFS, and it worked for me https://cloudflare-ipfs.com/ipfs/QmNpXBgqMCKiKcbSFGSuYLyUmkGd9LXaZA3HMP3hXtMJXX

2023-05-05 09:45 UTC, alfetopito approved these changes

2023-05-05 11:26 UTC, merged