add access button to the BV
cowprotocol/explorer pull request #73
Opened 2022-04-26 14:09 UTC by alongoni

# Summary

Closes #64 
![image](https://user-images.githubusercontent.com/622217/165318674-f9595f15-f687-4088-b7e7-b4478fad581b.png)

# To Test

1. <<Step one>> Open the page `about`
* <<What to expect?>> Verify it contains about information...
* Checkbox Style list of things a QA person could verify, i.e.
* Should display Text Input our storybook
* Input should not accept Numbers
2. <<Step two>> ...

# Background

*Optional: Give background information for changes you've made, that might be difficult to explain via comments*

2022-04-27 11:55 UTC, elena-zh approved these changes
LGTM!

2022-04-27 13:01 UTC, elena-zh commented
@alongoni , the only thing that I noticed here is that changes for the 'Copy' feature from #68 PR are not applied here

2022-04-27 19:54 UTC, ramirotw requested changes
Almost there, and please point the base branch to `41-anchor-url` which is @henrypalacios's branch

2022-04-27 19:54 UTC, ramirotw commented on src/components/orders/DetailsTable/index.tsx
> +                    <Button role="button">
This should trigger a route change so it makes sense for it be a Link and it should point to `to={`/tx/${txHash}/batch-graph`}`

2022-04-29 10:52 UTC, ramirotw commented on src/components/orders/DetailsTable/index.tsx
> +                    <Button role="button">
Update: url according to https://github.com/cowprotocol/explorer/pull/49 is `/tx/${txHash}/?tab=graph`

2022-04-29 17:51 UTC, ramirotw requested changes
could we move all the changes in the links and package.json to a different PR?

2022-04-29 17:53 UTC, ramirotw commented on src/components/orders/DetailsTable/index.tsx
> +                        <LinkWithPrefixNetwork to={`/tx/${txHash}/?tab=graph`}>{txHash}</LinkWithPrefixNetwork>
Sorry if I wasn't clear, this link shouldn't be changed, I was referring to the `View batch graph` button that needs to be a link that points to `/tx/${txHash}/?tab=graph`

2022-04-30 01:44 UTC, ramirotw requested changes
nice!! just 1 little thing and it's good to go.

Remove the underline during on-hover

<img width="139" alt="image" src="https://user-images.githubusercontent.com/3328006/166085752-68a0ae0b-9c12-4e29-af32-6d75afbca0c8.png">

2022-05-02 12:51 UTC, ramirotw approved these changes

2022-05-02 13:08 UTC, merged

2022-05-03 08:45 UTC, elena-zh commented
Hey @alongoni , I notices this weird issue in this PR
![image](https://user-images.githubusercontent.com/70885163/166426023-89df3c1e-eb16-4866-aae2-672a5dc86488.png)

It is reproducible when open TX list first, then to switch to the BV. See the video: https://watch.screencastify.com/v/15HqO9IiqlC1DV1dOTbt

But I was not able to reproduce the issue in #49 PR , so seems like it is fixed there. 
But could you please take a look and confirm that there is no need to worry about it? 

Thanks!

2022-05-03 10:56 UTC, ramirotw commented
@elena-zh that's correct, the base branch for this PR was set to @henrypalacios' branch, but when this PR was merged the issue you are pointing out was still present (now it's fixed)